services:
  backend:
    build:
      context: ./test-api
      dockerfile: Dockerfile
    container_name: flask_api
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/exampledb
    depends_on:
      - mongo

  frontend:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
